apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-app-volume-claim
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      volumeName: cloud-app-volume

# list existing persistent volumes claims: kubectl get pvc