apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloud-app-volume
  labels:
    volumeName: cloud-app-volume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /c/users/omen/desktop/de_invatat/pluralsight/kubernetes/volumes/html
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop


# list existing persistent volumes: kubectl get pv