apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-app-volume-claim
spec:
  accessModes:
    - ReadWriteMany
#  volumeMode: Filesystem
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
#  selector:
#    matchLabels:
#      volumeName: cloud-app-volume

# list existing persistent volumes claims: kubectl get pvc