apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: georgeciachir-dev
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: hello-pod
          image: georgeciachir/small-app:3.0 # if not otherwise specified, the image registry defaults to DockerHub
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: APP_SETTINGS_HTML_LOCATION # where the application files (such as the greeting html) volume is mounted
              valueFrom:
                configMapKeyRef:
                  name: app-settings
                  key: CONFIG_MAP_SETTINGS_htmlVolumeMountPath
            - name: APP_SETTINGS_DEFAULT_HTML_LOCATION
              valueFrom:
                configMapKeyRef:
                  name: app-settings
                  key: CONFIG_MAP_SETTINGS_defaultHtmlLocation
            - name: APP_SETTINGS_SETTINGS_LOCATION # where the settings volume is mounted
              valueFrom:
                configMapKeyRef:
                  name: app-settings
                  key: CONFIG_MAP_SETTINGS_settingsVolumeMountPath
            - name: APP_SETTINGS_SECRETS_LOCATION # where the secrets volume is mounted
              valueFrom:
                configMapKeyRef:
                  name: app-settings
                  key: CONFIG_MAP_SETTINGS_secretsVolumeMountPath
            - name: SECRET_APP_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-passwords
                  key: app-password
          envFrom:
            - configMapRef:
                name: app-settings

          volumeMounts:
            - name: pod-volume
              mountPath: /app-volume
              readOnly: false
            - name: app-settings-volume
              mountPath: /app-settings
              readOnly: true
            - name: secrets
              mountPath: /app-secrets
              readOnly: true
      volumes:
        - name: pod-volume
          persistentVolumeClaim:
            claimName: cloud-app-volume-claim
        - name: app-settings-volume
          configMap:
            name: app-settings
        - name: secrets
          secret:
            secretName: db-passwords